---
# Simple playbook that installs HTTPD, validates a correct HTML file to use, and starts the HTTPD service.
- name: Install and start Apache HTTPD
  hosts: web
  tasks:
    - name: httpd package is present
      yum:
        name: httpd
        state: present
        
    - name: correct index.html is present
      copy:
        src: webfiles/index.html
        dest: /var/www/html/index.html
        
    - name: httpd is started
      service:
        name: httpd
        state: started
        enabled: true
